# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DLGCi24wo-CCrYldJvmQQ8-ZFDIz3odT

✅ Grad-CAM 생성 함수
"""

def generate_gradcam(model, image, target_layer='layer4'):
    image = image.clone().detach().requires_grad_(True)
    activations = {}
    gradients = {}

    def forward_hook(module, input, output):
        activations['value'] = output

    def backward_hook(module, grad_in, grad_out):
        gradients['value'] = grad_out[0]

    layer = dict(model.named_modules())[target_layer]
    f_hook = layer.register_forward_hook(forward_hook)
    b_hook = layer.register_backward_hook(backward_hook)

    output = model(image)
    class_idx = output.argmax()
    model.zero_grad()
    output[0, class_idx].backward()

    pooled_grad = torch.mean(gradients['value'], dim=[0, 2, 3])
    activation = activations['value'][0]
    for i in range(activation.shape[0]):
        activation[i] *= pooled_grad[i]

    heatmap = activation.mean(0).cpu().numpy()
    heatmap = np.maximum(heatmap, 0)
    heatmap /= np.max(heatmap)

    f_hook.remove()
    b_hook.remove()
    return heatmap

"""✅ Heatmap 저장 함수"""

def save_heatmap(heatmap, image_tensor, path):
    import cv2
    heatmap = cv2.resize(heatmap, (image_tensor.shape[3], image_tensor.shape[2]))
    heatmap = np.uint8(255 * heatmap)
    heatmap_color = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)

    image_np = image_tensor.squeeze().permute(1, 2, 0).cpu().numpy()
    image_np = (image_np * 255).astype(np.uint8)

    overlay = cv2.addWeighted(image_np, 0.6, heatmap_color, 0.4, 0)
    cv2.imwrite(path, overlay)