# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DLGCi24wo-CCrYldJvmQQ8-ZFDIz3odT
"""

import os
import glob
import random
import json
import cv2
import PIL.Image as PILImage
import PIL.ImageTk as PILImageTk
from tkinter import *
from torchvision import transforms
from torchvision.utils import save_image
from torchvision.models import wide_resnet50_2
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm

# ----------------------- Data Loader -----------------------
class MVTecGoodDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        self.image_paths = sorted(glob.glob(os.path.join(root_dir, "*.png"))) + \
                           sorted(glob.glob(os.path.join(root_dir, "*.jpg")))
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        image = Image.open(img_path).convert("RGB")
        if self.transform:
            image = self.transform(image)
        return image, 0  # dummy label

# -------------------- LAS Augmentation ---------------------
def apply_las_augmentation(image, patch_size=64, stride=32):
    _, c, h, w = image.shape
    patches = []
    for i in range(0, h - patch_size + 1, stride):
        for j in range(0, w - patch_size + 1, stride):
            patch = image[:, :, i:i+patch_size, j:j+patch_size]
            patches.append(patch)
    random.shuffle(patches)
    new_image = torch.zeros_like(image)
    patch_idx = 0
    for i in range(0, h - patch_size + 1, stride):
        for j in range(0, w - patch_size + 1, stride):
            new_image[:, :, i:i+patch_size, j:j+patch_size] = patches[patch_idx]
            patch_idx += 1
    return new_image

# -------------------- GAS Augmentation ---------------------
def gas_augmentation_wrn(image, model=None, target_layer='layer4', steps=10, lr=0.01):
    image = image.clone().detach().requires_grad_(True)
    if model is None:
        model = wide_resnet50_2(pretrained=True)
        model.eval()
    activation = {}
    def hook_fn(module, input, output):
        activation['act'] = output
    handle = dict(model.named_modules())[target_layer].register_forward_hook(hook_fn)
    optimizer = torch.optim.SGD([image], lr=lr)
    for _ in range(steps):
        optimizer.zero_grad()
        model(image)
        act = activation['act']
        loss = -act.norm(p=2)
        loss.backward()
        optimizer.step()
    handle.remove()
    return image.detach()

# ---------------------- Save Augmented ---------------------
def save_augmented_dataset(data_path, save_root, las_fn, gas_fn, max_images=50):
    transform = transforms.Compose([transforms.Resize((256, 256)), transforms.ToTensor()])
    dataset = MVTecGoodDataset(data_path, transform)
    loader = DataLoader(dataset, batch_size=1, shuffle=True)
    os.makedirs(save_root, exist_ok=True)
    for sub in ["original", "las", "gas"]:
        os.makedirs(os.path.join(save_root, sub), exist_ok=True)
    model = wide_resnet50_2(pretrained=True).eval()
    for idx, (image, _) in enumerate(tqdm(loader)):
        if idx >= max_images:
            break
        image = image.cuda() if torch.cuda.is_available() else image
        las_img = las_fn(image)
        gas_img = gas_fn(image, model=model)
        save_image(image, os.path.join(save_root, "original", f"{idx:04d}.png"))
        save_image(las_img, os.path.join(save_root, "las", f"{idx:04d}.png"))
        save_image(gas_img, os.path.join(save_root, "gas", f"{idx:04d}.png"))

# ---------------------- Defect Generator ---------------------
def add_scratch_with_mask(img):
    h, w = img.shape[:2]
    mask = np.zeros((h, w), dtype=np.uint8)
    img_aug = img.copy()
    for _ in range(random.randint(1, 5)):
        x1, y1 = random.randint(0, w), random.randint(0, h)
        x2, y2 = x1 + random.randint(30, 100), y1 + random.randint(-20, 20)
        cv2.line(img_aug, (x1, y1), (x2, y2), (0, 0, 0), thickness=1)
        cv2.line(mask, (x1, y1), (x2, y2), 255, thickness=1)
    return img_aug, mask

def add_stain_with_mask(img):
    h, w = img.shape[:2]
    img_aug = img.copy()
    mask = np.zeros((h, w), dtype=np.uint8)
    stain = np.zeros_like(img)
    for _ in range(random.randint(1, 3)):
        center = (random.randint(0, w), random.randint(0, h))
        axes = (random.randint(10, 30), random.randint(10, 30))
        color = tuple([random.randint(30, 80) for _ in range(3)])
        cv2.ellipse(stain, center, axes, 0, 0, 360, color, -1)
        cv2.ellipse(mask, center, axes, 0, 0, 360, 255, -1)
    img_aug = cv2.addWeighted(img_aug, 1, stain, 0.5, 0)
    return img_aug, mask

def generate_defect_with_mask(img):
    return random.choice([add_scratch_with_mask, add_stain_with_mask])(img)

def augment_mvtec_with_mask(mvtec_root, class_name, num_per_image=3):
    input_dir = os.path.join(mvtec_root, class_name, "train", "good")
    test_output_dir = os.path.join(mvtec_root, class_name, "test", "synthetic")
    mask_output_dir = os.path.join(mvtec_root, class_name, "ground_truth", "synthetic")
    os.makedirs(test_output_dir, exist_ok=True)
    os.makedirs(mask_output_dir, exist_ok=True)
    image_paths = glob.glob(os.path.join(input_dir, "*.png")) + glob.glob(os.path.join(input_dir, "*.jpg"))
    for img_path in image_paths:
        img = cv2.imread(img_path)
        img_name = os.path.splitext(os.path.basename(img_path))[0]
        for i in range(num_per_image):
            defect_img, mask = generate_defect_with_mask(img)
            img_file = f"{img_name}_defect{i+1}.png"
            mask_file = f"{img_name}_defect{i+1}_mask.png"
            cv2.imwrite(os.path.join(test_output_dir, img_file), defect_img)
            cv2.imwrite(os.path.join(mask_output_dir, mask_file), mask)

# ------------------- User Feedback UI ----------------------
class GridFeedbackTool:
    def __init__(self, root, image_paths, save_dir, grid_size=3, image_size=220):
        self.root = root
        self.image_paths = image_paths
        self.save_dir = save_dir
        self.grid_size = grid_size
        self.image_size = image_size
        self.index = 0
        self.selected = {}
        self.feedback = {}
        self.root.title("사용자 피드백 툴")
        self.root.geometry(f"{grid_size * (image_size + 40)}x{grid_size * (image_size + 60) + 60}")
        self.root.configure(bg="white")
        self.frame = Frame(root, bg="white")
        self.frame.pack(pady=20)
        button_frame = Frame(root, bg="white")
        button_frame.pack(pady=5)
        Button(button_frame, text="다음 →", command=self.save_and_next).pack(side=LEFT, padx=10)
        Button(button_frame, text="저장 후 종료", command=self.save_and_quit).pack(side=LEFT, padx=10)
        Button(button_frame, text="종료", command=self.quit_without_saving).pack(side=LEFT, padx=10)
        self.root.bind("<s>", lambda e: self.save_and_quit())
        self.root.bind("<Escape>", lambda e: self.quit_without_saving())
        self.root.bind("<q>", lambda e: self.quit_without_saving())
        self.load_images()

    def load_images(self):
        for widget in self.frame.winfo_children():
            widget.destroy()
        self.current_batch = self.image_paths[self.index:self.index + self.grid_size**2]
        for idx, path in enumerate(self.current_batch):
            img = PILImage.open(path).resize((self.image_size, self.image_size))
            tk_img = PILImageTk.PhotoImage(img)
            label_frame = Frame(self.frame, bd=4, relief="solid")
            label_frame.grid(row=idx // self.grid_size, column=idx % self.grid_size, padx=10, pady=10)
            label = Label(label_frame, image=tk_img)
            label.image = tk_img
            label.pack()
            label.bind("<Button-1>", lambda e, p=path: self.toggle(p))
            label_frame.config(highlightthickness=4, highlightbackground=self.get_highlight_color(self.selected.get(path)))

    def get_highlight_color(self, status):
        return {"defect": "red", "good": "green"}.get(status, "gray")

    def toggle(self, path):
        current = self.selected.get(path)
        if current == "defect":
            self.selected[path] = "good"
        elif current == "good":
            del self.selected[path]
        else:
            self.selected[path] = "defect"
        self.load_images()

    def save_and_next(self):
        self.store_current_batch_feedback()
        self.index += self.grid_size**2
        if self.index < len(self.image_paths):
            self.load_images()
        else:
            self.save_feedback()
            self.root.quit()

    def save_and_quit(self):
        self.store_current_batch_feedback()
        self.save_feedback()
        self.root.quit()

    def quit_without_saving(self):
        self.root.quit()

    def store_current_batch_feedback(self):
        for path in self.current_batch:
            label = self.selected.get(path, "undecided")
            self.feedback[path] = label

    def save_feedback(self):
        os.makedirs(self.save_dir, exist_ok=True)
        txt_path = os.path.join(self.save_dir, "feedback.txt")
        json_path = os.path.join(self.save_dir, "feedback.json")
        with open(txt_path, "w") as f:
            for path, label in self.feedback.items():
                f.write(f"{path}\t{label}\n")
        with open(json_path, "w") as jf:
            json.dump(self.feedback, jf, indent=4)

# ---------------------- Entry Point ------------------------
if __name__ == "__main__":
    # 예시: 사용자 피드백 툴 실행
    image_dir = "./mvtec_anomaly_detection/hazelnut/test/synthetic"
    save_dir = "./user_feedback"
    image_paths = glob.glob(os.path.join(image_dir, "*.png"))

    root = Tk()
    app = GridFeedbackTool(root, image_paths, save_dir, grid_size=3, image_size=220)
    root.mainloop()